INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (1, 2, 'BBNG2', 2012);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (2, 3, 'Beats Vol.1', 2002);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (3, 4, 'Feijão com Arroz', 1996);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (4, 5, 'You''ll Understand', 2017);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (5, 2, 'III', 2014);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (6, 2, 'IV', 2016);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (7, 2, 'BBNG', 2011);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (8, 3, 'Pratica(mente)', 2006);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (9, 4, 'Música de Rua', 1994);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (10, 5, 'Don''t Sleep, There Are Snakes', 2017);
INSERT INTO albuns (id, id_banda, nome, ano_album) VALUES (11, 1, 'Dsdsasdasd', 22323237);